version: '3'
services:
  web1:
    container_name: web1
    image: 'jochanho/lb_apache2'
    networks:
      - mynet
  web2:
    container_name: web2
    image: 'jochanho/lb_nginx'
    networks:
      - mynet
  lb:
    container_name: lb
    image: 'jochanho/lb'
    volumes:
      - type: bind
        source: ./ubuntu_nginx_loadbalancer/nginx/sites-available
        target: /etc/nginx/sites-available
    networks:
      - mynet
    ports:
      - 80:80