version: '3'
services:
  web1:
    image: 'abhyuni/apache2'
    networks:
      - mynet
  web2:
    image: 'abhyuni/nginx'
    networks:
      - mynet
  lb:
    image: 'lb_nginx:v1.2'
    networks:
      - mynet
    ports:
      - 80:80
    depends_on:
      - web1
      - web2
networks:
  mynet: